# Generated by Django 4.1 on 2023-03-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Watchlist',
            new_name='watchlist',
        ),
    ]
